Modificación al blog

diff --git a/lb b/lb
--- a/lb
+++ b/lb
@@ -1,75 +1,76 @@
 #!/bin/bash
-
-# Set your personal data here:
+name="No Soy Anónimo"
+webdir="$(pwd)"
+website="https://nosoyanonimo.github.io/" # Keep a trailing slash.
+css="\/styles\/style.css"
+blogfile="2019.htm"
+indexfile="bloglist.htm"
 rssfile="rss.xml"
-blogfile="blog.htm"
-stylesheet="\/styles\/style.css"
-author="No Soy Anónimo"
-website="https://nosoyanonimo.github.io/"
-dir=$(pwd)
+[ -z "$EDITOR" ] && EDITOR="vim"
 
-getHelp() { \
-	echo -e "This system will take the blog entries you write and add them into the RSS file and HTML file of your choosing. Set which files to use by editing the 'lb' file directly and changing the variables at the top.\n"
-	echo -e "To fully prepare these files, add the following line to both files where you want the content to be added:\n"
-	echo -e "<!-- LB -->\n"
-	echo -e "Usage: 'new': create new draft; 'finalize': finish draft and add it to the RSS and HTML page; 'delete': delete a finished page.\n"
-	echo -e "As you finalize posts, they will be appended in the appropriate format below that line.\n"
-	echo -e "Blog posts will be stored in 'blog/' and drafts will be in 'blog/.drafts/'. To delete drafts, you only need delete their .html files directly, but use the 'lb delete' command to remove finalized posts since they appear in three places."
-}
+[ ! -d blog/.drafts ] &&
+read -erp "Initialize blog in $webdir?" ask &&
+	if [ "$ask" = "y" ]; then
+	printf "Initializing blog system...\\n"
+	mkdir -pv "$webdir/blog/.drafts" || printf "Error. Do you have write permissions in this directory?\\n"
+	echo "Options +Indexes" > "$webdir/blog/.htaccess"
+else
+	exit
+fi
 
-listandReturn() { \
-	#echo "Listing contents of $1."
-	echo "Enlistando los contenidos de $1."
-	ls $1 | nl
-	#read -p "Pick an entry by number to $2, or press ctrl-c to cancel. " number
-	read -p "Escoja una entrada por número para $2, o pulse ctrl-c para cancelar. " number
-	chosen=$(basename $(ls $1 | nl | grep -w  "$number" | awk '{print $2}'))
-	}
+newpost() { read -erp "Give a title for your post:
+	" title
+	echo "$title" | grep "\"" >/dev/null && printf "Double quotation marks (\") are not allowed in entry titles.\\n" && exit
+	url="$(echo "$title" | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')"
+	echo "AddDescription \"$title\" \"$url.html\"" >> "$webdir/blog/.htaccess" || { echo "Error: Is htaccess writeable?"; exit; }
+	[ -f "$webdir/blog/.drafts/$url.html" ] && echo "There is already an existing draft entry of that same name/URL." && exit
+	[ -f "$webdir/blog/$url.html" ] && echo "There is already an existing published entry of that same name/URL." && exit
+	$EDITOR "$webdir/blog/.drafts/$url.html" ;}
 
-getTitle() { \
-	#echo "Post will be stored as draft in $dir/blog/.drafts until finalized."
-	echo "El post se almacenará como borrador en $dir/blog/.drafts hasta que sea finalizado"
-	read -p "Escriba un título para su publicación: " title
-	url=$(echo $title | sed -e "s/'\|\"\|=\|+\|_\|,\|:\|;\|?\|!\|@\|\*\|&\|(\|)\|[\|]\|<\|>//g;s/ /-/g" | tr '[:upper:]' '[:lower:]') ;}
+listandReturn() { printf "Listing contents of %s.\\n" "$1"
+	ls -rc "$1" | awk -F '/' '{print $NF}' | nl
+	read -erp "Pick an entry by number to $2, or press ctrl-c to cancel. " number
+	chosen="$(ls -rc "$1" | nl | grep -w  "$number" | awk '{print $2}')"
+	basefile="$(basename "$chosen")" && base="${basefile%.*}" ;}
 
-postNew() { \
-	mkdir -p $dir/blog/.drafts
-	echo -e "<h2 id='$url'>$title</h2><small>[<a aria-hidden=\"true\" href=\"$blogfile#$url\">Enlace</a>&mdash;<a href=\"blog/$url.html\">Ir al post</a>]</small>\n\n<++>" >> $dir/blog/.drafts/$url.html && vim $dir/blog/.drafts/$url.html ;}
-
-finalize() { \
-	listandReturn $dir/blog/.drafts finalizar
-	url=$(cat $dir/blog/.drafts/$chosen | grep -o "<h2 id='\(.\)*'>" | cut -d "'" -f2)
-	title=$(cat $dir/blog/.drafts/$chosen | grep -o "<h2 id='\(.\)*h2>" |sed -e 's/<[^>]*>//g')
-	echo "AddDescription \"$title\" $chosen" >> $dir/blog/.htaccess
-	rssdate=$(date '+%a, %d %b %Y %H:%M:%S %z')
-	webdate=$(date '+%a, %d %b %Y %H:%M:%S %z')
+publish() { \
+	delete
+	htaccessentry=$(grep "$basefile" "$webdir/blog/.htaccess")
+	realname="$(echo "$htaccessentry" | cut -d'"' -f2)"
+	rssdate="$(grep "$basefile" blog/.htaccess | sed "s/.*\.html\"* *#*//g" | tr -d '\n')"
+	[ -z "$rssdate" ] && rssdate="$(date '+%a, %d %b %Y %H:%M:%S %z')" # RSS date formats must comply with standards to validate.
+	webdate="$(date '+%a, %d %b %Y %H:%M:%S %z')" # But this visible date you can set to any format.
 	tmpdir=$(mktemp -d)
-	echo -e "\n<item>\n<title>$title</title>\n<guid>$website$blogfile#$url</guid>\n<pubDate>$rssdate</pubDate>\n<description><![CDATA[\n$(cat $dir/blog/.drafts/$chosen)\n]]></description>\n</item>\n"> $tmpdir/rss.xml
-	echo -e "\n<article>\n$(cat $dir/blog/.drafts/$chosen)\n<small>$webdate <b>por </b> $author</small>\n</article>\n" > $tmpdir/html.html
-	sed -i "/<!-- LB -->/r $tmpdir/html.html" $blogfile
-	sed -i "/<!-- LB -->/r $tmpdir/rss.xml" $rssfile
-	header="<html>\n<head>\n<title>$title<\/title>\n<link rel='stylesheet' type='text\/css' href='$stylesheet'>\n<meta charset='utf-8'\/>\n<\/head>\n<body>"
-	footer="<\/body>\n<footer>por <strong>$author<\/strong><\/footer>\n<\/html>"
-	sed  "s/href=\"/href=\"..\//g;s/\.\.\/http/http/g;0,/^/s//$header/;0,/<h2 id=/s//<h1 id=/;0,/h2>/s//h1>/;\$a$footer" $dir/blog/.drafts/$chosen > $dir/blog/$chosen
-	rm $dir/blog/.drafts/$chosen
+	printf "<html>\\n<head>\\n<title>%s</title>\\n<link rel='stylesheet' type='text/css' href='%s'>\\n<meta charset='utf-8'/>\\n</head>\\n<body>\\n<h1>%s</h1>\\n<small>[<a href='%s#%s'>Enlace</a>&mdash;<a href='%s'>Ir al post</a>]</small>\\n%s\\n<footer>by <strong><a href='%s'>%s</a></strong></footer>\\n</body>\\n\\n</html>" "$realname" "$css" "$realname" "../$blogfile" "$base" "$basefile" "$(cat "$webdir/blog/.drafts/$basefile")" "$website" "$name" > "$webdir/blog/$basefile"
+	printf "\\n<item>\\n<title>%s</title>\\n<guid>%s%s#%s</guid>\\n<pubDate>%s</pubDate>\\n<description><![CDATA[\\n%s\\n]]></description>\\n</item>\\n\\n" "$realname" "$website" "$blogfile" "$basefile" "$rssdate" "$(cat "$webdir/blog/.drafts/$basefile")" >  "$tmpdir/rss"
+	printf "<article>\\n<h2 id='%s'>%s</h2>\\n<small>[<a href='#%s'>Enlace</a>&mdash;<a href='%s'>Ir al blog</a>]</small>\\n%s\\n<small>%s</small>\\n</article>\\n" "$base" "$realname" "$base" "blog/$basefile" "$(cat "$webdir/blog/.drafts/$basefile")" "$webdate" > "$tmpdir/html"
+	printf "<li>%s &ndash; <a href=\"blog/%s\">%s</a></li>\\n" "$(date '+%Y %b %d')" "$basefile" "$realname" > "$tmpdir/index"
+	sed -i "/<!-- LB -->/r $tmpdir/html" "$blogfile"
+	sed -i "/<!-- LB -->/r $tmpdir/rss" "$rssfile"
+	sed -i "/<!-- LB -->/r $tmpdir/index" "$indexfile"
+	sed -i "/ \"$base.html\"/d" "$webdir/blog/.htaccess"
+	echo "AddDescription \"$realname\" \"$basefile\" #$rssdate" >> "$webdir/blog/.htaccess"
+	rm -f "$webdir/blog/.drafts/$chosen"
 }
+
+confirm() { read -erp "Really $1 \"$base\"? (y/N) " choice && echo "$choice" | grep -i "^y$" >/dev/null || exit 1 ;}
 
 delete() { \
-	listandReturn "$dir/blog/*.html" eliminar
-	base=$(echo $chosen | cut -f1 -d'.')
-	read -p "¿En verdad desea eliminar \"$base\"? (s,N) " choice
-	[[ $choice =~ [Ss] ]] || exit
-	#rm $dir/blog/$chosen && echo "Blog post deleted from directories."
-	rm $dir/blog/$chosen && echo "La entrada del blog fue eliminada de los directorios"
-	#sed -i "/<item/{:a;N;/<\/item>/!ba};/$base/d" $rssfile && echo "Entry removed from RSS feed file."
-	sed -i "/<item/{:a;N;/<\/item>/!ba};/$base/d" $rssfile && echo "La entrada fue eliminada del archivo RSS"
-	#sed -i "/<article/{:a;N;/<\/article>/!ba};/$base/d" $blogfile && echo "HTML code removed from blogfile."
-	sed -i "/<article/{:a;N;/<\/article>/!ba};/$base/d" $blogfile && echo "Código HTML eliminado del archivo del blog."
-	}
+	sed -i "/<item/{:a;N;/<\\/item>/!ba};/#$base.html<\\/guid/d" $rssfile
+	sed -i "/<div/{:a;N;/<\\/div>/!ba};/id='$base'/d" $blogfile
+	sed -i "/<li>.*<a href=\"blog\\/$base.html\">/d" $indexfile
+	rm "$webdir/blog/$basefile" 2>/dev/null && printf "Old blog entry removed.\\n" ;}
+
+revise() { awk '/^<small>\[/{flag=1;next}/<footer>/{flag=0}flag' "$webdir/blog/$chosen" > "$webdir/blog/.drafts/$basefile"
+	"$EDITOR" "$webdir/blog/.drafts/$basefile"
+	printf "Revision stored in blog/.drafts. Publish as normal entry when desired.\\n" ;}
 
 case "$1" in
-	new) getTitle && postNew ;;
-	finalize) finalize ;;
-	delete) delete ;;
-	*) getHelp ;;
+	n*) newpost ;;
+	e*) listandReturn "$webdir"/blog/.drafts/ edit && "$EDITOR" "$webdir/blog/.drafts/$chosen" ;;
+	p*) listandReturn "$webdir"/blog/.drafts/ publish && publish ;;
+	t*) listandReturn "$webdir"/blog/.drafts/ trash && confirm trash && rm -f "$webdir/blog/.drafts/$chosen" && sed -i "/ \"$base.html\"/d" "$webdir/blog/.htaccess" ; printf "Draft deleted.\\n" ;;
+	d*) listandReturn "$webdir"/blog/ delete && confirm delete && delete ;;
+	r*) listandReturn "$webdir"/blog/ revise && revise ;;
+	*) printf "lb blog system by Luke Smith <luke@lukesmith.xyz>\\nUsage:\\n  ln n:\\tnew draft\\n  lb e:\\tedit draft\\n  lb p:\\tpublish/finalize draft\\n  lb r:\\trevise published entry\\n  lb t:\\tdiscard draft\\n  lb d:\\tdelete published entry\\n\\nBe sure to have the following pattern added to your RSS feed, blog file and blog index:\\n\\n<!-- LB -->\\n\\nNew content will be added directly below that sequence. This is required.\\nSee https://github.com/LukeSmithxyz/lb for more.\\n" ;;
 esac
